### PR TITLE
invisible property and show()/hide() methods added for View

### PR DESCRIPTION
**Pull request by illuzor**
Additional for #23
Not sure what do you think about it.
I believe it will be useful.

### CODE REVIEW

**Comment by pawegio** [comment]
I would prefer to keep just one way to update `visibility` to stay concise. I like `show()/hide()` methods, because it allows to set `View.INVISIBLE` state.

**Comment by illuzor** [comment]
I have to remove **invisible**? Or just close this pull request?
Or maybe remove visible and invisible and leave hide()/show()? I don`t clearly understand.

**Comment by pawegio** [comment]
I suggest removing visible/invisible properties and keep hide()/show() methods. What do you think?

**Comment by illuzor** [comment]
I agree about **invisible**. Two properties with opposite values is not good.
I suggest keep **hide()**/**show()** and **visible**.
**visible** may be useful for situations like this:

```kotlin
myView.visible = someInt > 3
```

But this is your library and final decision is yours.

**Comment by pawegio** [comment]
Ok, thanks for providing a use case. Now I am convinced to keep both `visible` and `show()`/`hide()`. Only `invisible` seems redundant to me.

**Comment by pawegio** [comment]
So remove `invisible` and I'll merge it. 🙂

**Comment by pawegio** [comment]
👍

**Pull request merged**
