### PR TITLE
Test for KView and KViewGroup

### PR DESCRIPTION
**Pull request by illuzor**

### CODE REVIEW

**Comment by pawegio** [comment]
Thanks, now just update travis build script to run `connectedCheck` task after build. You'll also need to create and run android emulator. If you have any problems with this, let me know so I'll assist you.

**Comment by illuzor** [comment]
I can`t realize how to run emulator on travis without errors

**Comment by illuzor** [comment]
Fixed

**Comment by pawegio** [comment]
Cool, great job! 💯

**Pull request merged**
